### ISSUE TITLE
Добавить web api админ клиент

### ISSUE THREAD

**Issue by vaspahomov** [complexitybot/Quiz#44]

**Comment by FunFunFine** [comment]
Второй контроллер в `QuizWebApi`;
Необходимо добавить некоторую Cookie с паролем или токеном.
Админка должна уметь:
* Добавлять уровень в выбранный топик
* Добавлять топик
* Добавлять генератор в выбранный уровень
* Удалять генератор
* Удалять уровень
* Удалять топик
Админка не проверяет, есть ли уже такая сущность при добавлении, просто пишем рядом.
