### ISSUE TITLE
После прохождения уровня пользователю не понятно, что делать дальше

### ISSUE THREAD

**Issue by xoposhiy** [complexitybot/Quiz#74]
После прохождения первого уровня, бот пишет прогресс, а новую задачу не дает. Пользователю не понятно, что делать дальше.

![image](https://user-images.githubusercontent.com/856752/56848778-3287ed80-6906-11e9-8151-ce01c4cfa461.png)

Нужно явно предложить либо перейти на следующий уровень, либо взять ещё задачку.

**Comment by FunFunFine** [comment]
Добавить `LevelEndState` и два перехода из него: `TaskSelectionTransition` и `LevelSelectionTransition`
