### ISSUE TITLE
Упростить старт диалога с ботом

### ISSUE THREAD

**Issue by xoposhiy** [complexitybot/Quiz#75]
1. В первом же сообщении бот должен рассказать про себя.
2. Это же описание можно повторять каждый раз на глобальную команду /help (можно ее зарегать в BotFather и она всегда будет доступна в кнопке [ / ] рядом с полем ввода сообщения). 
3. Список ваших контактов лучше перенести в описание бота.
(Кому именно писать-то, кстати? Не парьте пользователям мозг напишите один контакт, в который можно писать предложения и баги). 
4. Тогда можно не делать кнопки "справка" и "обратная связь". А вместо кнопки порешать, сразу дать выбрать тему.

Примерно так:

/start

Привет! Я бот такой-то, делают то-то и то-то. Решай задачки, открывай новые уровни, всё такое. Умею в несколько тем. Выбирай тему и начинай!

[Сложность алгоритмов]
[Битовые операции]
[Орфография]

**Comment by FunFunFine** [comment]
Хорошо бы завести аккаунт или бота (такие есть у BotFather или в чем-то таком) для фидбека, как у юлерна например есть почта отдельная
