### ISSUE TITLE
Не показывать кнопки "подсказка" и "дальше", когда на них нельзя нажать

### ISSUE THREAD

**Issue by xoposhiy** [complexitybot/Quiz#76]
Если нет подсказок, не показывать Подсказку
Пока не дал ответ на задачу, не показывать Дальше (или вообще никогда не показывать? Зачем она?)

**Comment by FunFunFine** [comment]
С кнопкой `Дальше` все сложнее -- нужно будет переработать обработку ответа, так как сейчас она находится в ICommand и не может менять состояние. 
Нужно рефакторить это.
