### ISSUE TITLE
Отображать степени красиво Θ(n²) вместо Θ(n^2)

### ISSUE THREAD

**Issue by xoposhiy** [complexitybot/Quiz#78]
Надстрочные цифры есть в юникоде:

* ² и ³ тут: https://unicode-table.com/ru/blocks/latin-1-supplement/
* ⁴ и остальные тут: https://unicode-table.com/ru/blocks/superscripts-and-subscripts/

**Comment by FunFunFine** [comment]
Два варианта:
* Сразу записывать в базу данных так, как надо
* На этапе генерации таска заменять по регулярке
